code = {
    "getSunriseWithElevation": "ZmanPrimitive::ElevationAdjustedSunrise",
    "getSeaLevelSunrise": "ZmanPrimitive::SeaLevelSunrise",
    "getSunsetWithElevation": "ZmanPrimitive::ElevationAdjustedSunset",
    "getSeaLevelSunset": "ZmanPrimitive::SeaLevelSunset",
    "getAlos60Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunrise, Duration::from_mins(-60))",
    "getAlos72Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunrise, Duration::from_mins(-72))",
    "getAlos72Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunrise, -1.2)",
    "getAlos90Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunrise, Duration::from_mins(-90))",
    "getAlos90Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunrise, -1.5)",
    "getAlos96Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunrise, Duration::from_mins(-96))",
    "getAlos96Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunrise, -1.6)",
    "getAlos120Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunrise, Duration::from_mins(-120))",
    "getAlos120Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunrise, -2.0)",
    "getAlos16Point1Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(16.1)",
    "getAlos18Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(18.0)",
    "getAlos19Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(19.0)",
    "getAlos19Point8Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(19.8)",
    "getAlos26Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(26.0)",
    "getAlosBaalHatanya": "ZmanPrimitive::SunriseOffsetByDegrees(16.9)",
    "getBainHashmashosRT13Point24Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(13.24)",
    "getBainHashmashosRT2Stars": "ZmanPrimitive::BainHashmashosRt2Stars",
    "getBainHashmashosYereim18Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(-18))",
    "getBainHashmashosYereim2Point1Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(-2.1)",
    "getBainHashmashosYereim2Point8Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(-2.8)",
    "getBainHashmashosYereim3Point05Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(-3.05)",
    "getCandleLighting": "ZmanPrimitive::CandleLighting",
    "getChatzosHayom": "ZmanPrimitive::SolarTransit",
    "getChatzosHalayla": "ZmanPrimitive::SolarMidnight",
    "getFixedLocalChatzosHayom": "ZmanPrimitive::LocalMeanTime(12.0)",
    "getMinchaGedola30Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::SolarTransit, Duration::from_mins(30))",
    "getMinchaGedolaAhavatShalom": "ZmanPrimitive::MinchaGedolaAhavatShalom",
    "getMinchaGedolaGRAFixedLocalChatzos30Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::LocalMeanTime(12.0), Duration::from_mins(30))",
    "getMinchaKetanaAhavatShalom": "ZmanPrimitive::MinchaKetanaAhavatShalom",
    "getMisheyakir10Point2Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(10.2)",
    "getMisheyakir11Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(11.0)",
    "getMisheyakir11Point5Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(11.5)",
    "getMisheyakir12Point85Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(12.85)",
    "getMisheyakir7Point65Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(7.65)",
    "getMisheyakir9Point5Degrees": "ZmanPrimitive::SunriseOffsetByDegrees(9.5)",
    "getPlagAhavatShalom": "ZmanPrimitive::PlagAhavatShalom",
    "getSofZmanShma3HoursBeforeChatzos": "ZmanPrimitive::Offset(&ZmanPrimitive::SolarTransit, Duration::from_mins(-180))",
    "getSofZmanTfila2HoursBeforeChatzos": "ZmanPrimitive::Offset(&ZmanPrimitive::SolarTransit, Duration::from_mins(-120))",
    "getTzaisGeonim8Point5Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(8.5)",
    "getTzais50Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(50))",
    "getTzais60Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(60))",
    "getTzais72Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(72))",
    "getTzais72Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunset, 1.2)",
    "getTzais90Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(90))",
    "getTzais90Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunset, 1.5)",
    "getTzais96Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(96))",
    "getTzais96Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunset, 1.6)",
    "getTzais120Minutes": "ZmanPrimitive::Offset(&ZmanPrimitive::ConfiguredSunset, Duration::from_mins(120))",
    "getTzais120Zmanis": "ZmanPrimitive::ZmanisOffset(&ZmanPrimitive::ConfiguredSunset, 2.0)",
    "getTzais16Point1Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(16.1)",
    "getTzais18Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(18.0)",
    "getTzais19Point8Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(19.8)",
    "getTzais26Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(26.0)",
    "getTzaisAteretTorah": "ZmanPrimitive::TzaisAteretTorah",
    "getTzaisBaalHatanya": "ZmanPrimitive::SunsetOffsetByDegrees(6.0)",
    "getTzaisGeonim3Point7Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(3.7)",
    "getTzaisGeonim3Point8Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(3.8)",
    "getTzaisGeonim5Point95Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(5.95)",
    "getTzaisGeonim4Point66Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(4.66)",
    "getTzaisGeonim4Point42Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(4.42)",
    "getTzaisGeonim4Point8Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(4.8)",
    "getTzaisGeonim6Point45Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(6.45)",
    "getTzaisGeonim7Point083Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(7.0 + (5.0 / 60.0))",
    "getTzaisGeonim7Point67Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(7.67)",
    "getTzaisGeonim9Point3Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(9.3)",
    "getTzaisGeonim9Point75Degrees": "ZmanPrimitive::SunsetOffsetByDegrees(9.75)",
    "getSofZmanKidushLevana15Days": "ZmanPrimitive::SofZmanKidushLevana15Days",
    "getSofZmanKidushLevanaBetweenMoldos": "ZmanPrimitive::SofZmanKidushLevanaBetweenMoldos",
    "getTchilasZmanKidushLevana3Days": "ZmanPrimitive::TchilasZmanKidushLevana3Days",
    "getTchilasZmanKidushLevana7Days": "ZmanPrimitive::TchilasZmanKidushLevana7Days",
    "getZmanMolad": "ZmanPrimitive::Molad",
}
