//! Test policy for Hebrew-date Java parity checks.

use std::{env, sync::OnceLock};

/// Default number of randomized cases in the Hebrew-date parity suite.
///
/// Hebrew-date checks compare several operations per case, so this is lower
/// than the per-preset zmanim default while still covering many calendar edges.
pub(super) const DEFAULT_HEBREW_DATE_PARITY_ITERATIONS: u64 = 1_000;

/// Inclusive Gregorian year range used for randomized Hebrew-date parity cases.
pub(super) const MIN_GREGORIAN_YEAR: i32 = 1900;
pub(super) const MAX_GREGORIAN_YEAR: i32 = 2100;

/// Day offsets applied to random and regression Jewish dates.
pub(super) const DAY_OFFSETS: &[i32] = &[0, 1, -1, 29, -29, 365, -365];

/// Month offsets applied to random and regression Jewish dates.
pub(super) const MONTH_OFFSETS: &[i32] = &[0, 1, -1, 6, -6, 12];

/// Year offsets applied to random and regression Jewish dates.
pub(super) const YEAR_OFFSETS: &[i32] = &[0, 1, -1, 5, -5];

/// Number of randomized cases to run for the Hebrew-date parity suite.
///
/// Set `ZMANIM_HEBREW_DATE_JAVA_PARITY_ITERATIONS` to raise or lower this when
/// debugging calendar behavior. This only affects `test_hebrew_date_parity`.
pub(super) fn test_iterations() -> u64 {
    read_env_u64(
        "ZMANIM_HEBREW_DATE_JAVA_PARITY_ITERATIONS",
        DEFAULT_HEBREW_DATE_PARITY_ITERATIONS,
    )
}

/// Inclusive Jewish year range generated by the Hebrew-date parity suite.
pub(super) fn jewish_year_range() -> (i32, i32) {
    (MIN_GREGORIAN_YEAR + 3760, MAX_GREGORIAN_YEAR + 3760)
}

/// Seed used by randomized test cases.
///
/// Set `ZMANIM_JAVA_PARITY_SEED` to replay a failure reported by the parity harness.
pub(super) fn test_seed() -> u64 {
    static SEED: OnceLock<u64> = OnceLock::new();

    *SEED.get_or_init(|| match env::var("ZMANIM_JAVA_PARITY_SEED") {
        Ok(value) => value
            .parse::<u64>()
            .unwrap_or_else(|_| panic!("invalid ZMANIM_JAVA_PARITY_SEED value: {value}")),
        Err(env::VarError::NotPresent) => rand::random::<u64>(),
        Err(err) => panic!("failed to read ZMANIM_JAVA_PARITY_SEED: {err}"),
    })
}

fn read_env_u64(var_name: &str, default: u64) -> u64 {
    match env::var(var_name) {
        Ok(value) => value
            .parse::<u64>()
            .unwrap_or_else(|_| panic!("invalid {var_name} value: {value}")),
        Err(env::VarError::NotPresent) => default,
        Err(err) => panic!("failed to read {var_name}: {err}"),
    }
}
